// Deterministic contract generation. No network, no model calls.
//   bun scripts/codegen.ts            -> writes generated/
//   bun scripts/codegen.ts <outDir>   -> writes elsewhere (used by check-drift)
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import Ajv2020 from "ajv/dist/2020";
import standaloneCode from "ajv/dist/standalone";
import { compile } from "json-schema-to-typescript";

const root = resolve(import.meta.dirname, "..");
const schemaDir = join(root, "contracts/schemas");
const outDir = resolve(process.argv[2] ?? join(root, "generated"));
const banner =
	"// GENERATED by scripts/codegen.ts from contracts/. Do not edit. Run `bun run codegen`.\n";

const files = readdirSync(schemaDir)
	.filter((f) => f.endsWith(".schema.json"))
	.sort();
const schemas = files.map((f) =>
	JSON.parse(readFileSync(join(schemaDir, f), "utf8")),
);
const registry = JSON.parse(
	readFileSync(join(root, "contracts/operations.json"), "utf8"),
);

// ---- validators (Ajv standalone, strict) ----
const ajv = new Ajv2020({
	strict: true,
	allErrors: true,
	code: { source: true, esm: true, lines: true },
});
for (const s of schemas) ajv.addSchema(s);

const exportName = (ref: string) =>
	ref.includes("#/$defs/")
		? (ref.split("#/$defs/")[1] as string)
		: (schemas.find((s) => s.$id === ref)?.title as string);

const validatorRefs: Record<string, string> = {};
for (const s of schemas) {
	if (s.type === "object" || s.oneOf) validatorRefs[s.title] = s.$id;
	if (s.$id === "requests.schema.json")
		for (const k of Object.keys(s.$defs))
			validatorRefs[k] = `${s.$id}#/$defs/${k}`;
}
for (const op of registry.operations)
	for (const ref of [op.request, op.response, op.entries].filter(Boolean))
		if (!ajv.getSchema(ref))
			throw new Error(`${op.operationId}: unresolved schema ref ${ref}`);

const sortedRefs = Object.fromEntries(
	Object.entries(validatorRefs).sort(([a], [b]) => a.localeCompare(b)),
);
const validatorsJs = banner + standaloneCode(ajv, sortedRefs);
const validatorsDts = `${banner}import type { ErrorObject } from "ajv";
export interface Validator { (data: unknown): boolean; errors?: ErrorObject[] | null }
${Object.keys(sortedRefs)
	.map((n) => `export declare const ${n}: Validator;`)
	.join("\n")}
`;

// ---- types (one bundle so shared definitions are declared once) ----
const bundle = {
	title: "ThinkWideContract",
	type: "object",
	additionalProperties: false,
	properties: Object.fromEntries(
		Object.entries(sortedRefs).map(([name, ref]) => [name, { $ref: ref }]),
	),
};
const types = await compile(bundle as never, "ThinkWideContract", {
	cwd: schemaDir,
	bannerComment: banner.trim(),
	additionalProperties: false,
	unreachableDefinitions: false,
	format: false,
	strictIndexSignatures: true,
});

// ---- operations ----
const ops = registry.operations.map((op: Record<string, unknown>) => ({
	...op,
	requestType: exportName(op.request as string),
	responseType: exportName(op.response as string),
	entriesType: op.entries ? exportName(op.entries as string) : null,
}));
const operationsTs = `${banner}export const CONTRACT_VERSION = ${JSON.stringify(registry.contractVersion)} as const;

export const OPERATIONS = ${JSON.stringify(ops, null, "\t")} as const;

export type OperationId = (typeof OPERATIONS)[number]["operationId"];
export type EffectClass = "read" | "state" | "external";
export const MCP_EXPOSED: readonly OperationId[] = OPERATIONS.filter((o) =>
	(o.exposure as readonly string[]).includes("mcp"),
).map((o) => o.operationId);
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "validators.js"), validatorsJs);
writeFileSync(join(outDir, "validators.d.ts"), validatorsDts);
writeFileSync(join(outDir, "types.ts"), types);
writeFileSync(join(outDir, "operations.ts"), operationsTs);
console.log(
	`codegen: ${files.length} schemas, ${Object.keys(sortedRefs).length} validators, ${ops.length} operations -> ${outDir}`,
);
