// Deterministic contract generation. No network, no model calls.
//   bun scripts/codegen.ts            -> writes generated/
//   bun scripts/codegen.ts <outDir>   -> writes elsewhere (used by check-drift)
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import Ajv2020 from "ajv/dist/2020";
import standaloneCode from "ajv/dist/standalone";
import { compile } from "json-schema-to-typescript";

const root = resolve(import.meta.dirname, "..");
const schemaDir = join(root, "contracts/schemas");
const outDir = resolve(process.argv[2] ?? join(root, "generated"));
const banner =
	"// GENERATED by scripts/codegen.ts from contracts/. Do not edit. Run `bun run codegen`.\n";

const files = readdirSync(schemaDir)
	.filter((f) => f.endsWith(".schema.json"))
	.sort();
const schemas = files.map((f) =>
	JSON.parse(readFileSync(join(schemaDir, f), "utf8")),
);
const registry = JSON.parse(
	readFileSync(join(root, "contracts/operations.json"), "utf8"),
);

// ---- validators (Ajv standalone, strict) ----
const ajv = new Ajv2020({
	strict: true,
	allErrors: true,
	code: { source: true, esm: true, lines: true },
});
for (const s of schemas) ajv.addSchema(s);

const exportName = (ref: string) =>
	ref.includes("#/$defs/")
		? (ref.split("#/$defs/")[1] as string)
		: (schemas.find((s) => s.$id === ref)?.title as string);

const validatorRefs: Record<string, string> = {};
for (const s of schemas) {
	if (s.type === "object" || s.oneOf) validatorRefs[s.title] = s.$id;
	if (s.$id === "requests.schema.json")
		for (const k of Object.keys(s.$defs))
			validatorRefs[k] = `${s.$id}#/$defs/${k}`;
}
const envelopeKinds: string[] = schemas.find(
	(s) => s.$id === "envelope.schema.json",
).properties.kind.enum;
for (const op of registry.operations) {
	const isEnvelope = op.response === "envelope.schema.json";
	if (isEnvelope && !envelopeKinds.includes(op.envelopeKind))
		throw new Error(
			`${op.operationId}: envelope response needs envelopeKind in [${envelopeKinds}]`,
		);
	if (!isEnvelope && op.envelopeKind !== undefined)
		throw new Error(
			`${op.operationId}: envelopeKind is only valid on envelope responses`,
		);
}
for (const op of registry.operations)
	for (const ref of [op.request, op.response, op.entries].filter(Boolean))
		if (!ajv.getSchema(ref))
			throw new Error(`${op.operationId}: unresolved schema ref ${ref}`);

const sortedRefs = Object.fromEntries(
	Object.entries(validatorRefs).sort(([a], [b]) => a.localeCompare(b)),
);
// Ajv standalone emits CommonJS `require("ajv/dist/runtime/<name>").default` even in ESM mode.
// A bare require is not safe in Convex or browser bundles, so hoist each one into an ESM import.
// The runtime files are CommonJS with `exports.default = fn`: Node's ESM interop hands back the
// module.exports object, while bundlers honouring __esModule hand back fn itself. Accept both.
const runtimeRequire =
	/^const (\w+) = require\("(ajv\/dist\/runtime\/\w+)"\)\.default;$/gm;
const runtimeImports: string[] = [];
const standaloneEsm = standaloneCode(ajv, sortedRefs).replace(
	runtimeRequire,
	(_line, local: string, specifier: string) => {
		runtimeImports.push(`import ${local}_mod from "${specifier}.js";\n`);
		return `const ${local} = typeof ${local}_mod === "function" ? ${local}_mod : ${local}_mod.default;`;
	},
);
const validatorsJs = banner + runtimeImports.sort().join("") + standaloneEsm;
if (validatorsJs.includes("require("))
	throw new Error(
		"codegen: generated validators still contain require(); extend the runtime import rewrite",
	);
const validatorsDts = `${banner}import type { ErrorObject } from "ajv";
export interface Validator { (data: unknown): boolean; errors?: ErrorObject[] | null }
${Object.keys(sortedRefs)
	.map((n) => `export declare const ${n}: Validator;`)
	.join("\n")}
`;

// ---- types (one bundle so shared definitions are declared once) ----
const bundle = {
	title: "ThinkWideContract",
	type: "object",
	additionalProperties: false,
	properties: Object.fromEntries(
		Object.entries(sortedRefs).map(([name, ref]) => [name, { $ref: ref }]),
	),
};
const types = await compile(bundle as never, "ThinkWideContract", {
	cwd: schemaDir,
	bannerComment: banner.trim(),
	additionalProperties: false,
	unreachableDefinitions: false,
	format: false,
	strictIndexSignatures: true,
});

// ---- operations ----
const EFFECTS = ["read", "state", "external"] as const;
const handlerPattern = /^[A-Za-z][A-Za-z0-9_/]*:[A-Za-z_$][A-Za-z0-9_$]*$/;
const ops = registry.operations.map((op: Record<string, unknown>) => ({
	...op,
	requestType: exportName(op.request as string),
	responseType: exportName(op.response as string),
	entriesType: op.entries ? exportName(op.entries as string) : null,
}));
const seenIds = new Set<string>();
const seenHandlers = new Map<string, string>();
for (const op of ops) {
	if (seenIds.has(op.operationId))
		throw new Error(`${op.operationId}: duplicate operationId`);
	seenIds.add(op.operationId);
	if (!EFFECTS.includes(op.effect))
		throw new Error(`${op.operationId}: effect must be one of [${EFFECTS}]`);
	if (!op.requestType || !op.responseType)
		throw new Error(`${op.operationId}: request/response has no named type`);
	if (op.handler === undefined) continue;
	if (typeof op.handler !== "string" || !handlerPattern.test(op.handler))
		throw new Error(
			`${op.operationId}: handler must be "<convexModule>:<exportName>"`,
		);
	const other = seenHandlers.get(op.handler);
	if (other)
		throw new Error(
			`${op.operationId}: handler ${op.handler} is already bound to ${other}`,
		);
	seenHandlers.set(op.handler, op.operationId);
}
// Registry order everywhere, so output is a pure function of contracts/.
const typeMap = (name: string, field: "requestType" | "responseType") =>
	`export type ${name} = {\n${ops
		.map((o: Record<string, string>) => `\t${o.operationId}: ${o[field]};`)
		.join("\n")}\n};`;
const effectUnion = (name: string, effect: string) => {
	const ids = ops
		.filter((o: Record<string, string>) => o.effect === effect)
		.map((o: Record<string, string>) => JSON.stringify(o.operationId));
	return `export type ${name} = ${ids.length ? ids.join(" | ") : "never"};`;
};
const importedTypes = [
	...new Set(
		ops.flatMap((o: Record<string, string>) => [o.requestType, o.responseType]),
	),
].sort() as string[];
const unimplemented = ops
	.filter((o: Record<string, unknown>) => o.handler === undefined)
	.map((o: Record<string, string>) => o.operationId);
const operationsTs = `${banner}import type {
${importedTypes.map((t) => `\t${t},`).join("\n")}
} from "./types";

export const CONTRACT_VERSION = ${JSON.stringify(registry.contractVersion)} as const;

export const OPERATIONS = ${JSON.stringify(ops, null, "\t")} as const;

export type OperationId = (typeof OPERATIONS)[number]["operationId"];
export type EffectClass = "read" | "state" | "external";
export const MCP_EXPOSED: readonly OperationId[] = OPERATIONS.filter((o) =>
	(o.exposure as readonly string[]).includes("mcp"),
).map((o) => o.operationId);

/** Request and response type of every registered operation, from requestType / responseType. */
${typeMap("OperationRequestMap", "requestType")}
${typeMap("OperationResponseMap", "responseType")}

/** Operation ids by effect class. */
${effectUnion("ReadOperationId", "read")}
${effectUnion("StateOperationId", "state")}
${effectUnion("ExternalOperationId", "external")}

/** "<convexModule>:<exportName>" of the Convex function implementing each operation. */
export const OPERATION_HANDLERS = ${JSON.stringify(
	Object.fromEntries(
		ops
			.filter((o: Record<string, unknown>) => o.handler !== undefined)
			.map((o: Record<string, string>) => [o.operationId, o.handler]),
	),
	null,
	"\t",
)} as const;
export type ImplementedOperationId = keyof typeof OPERATION_HANDLERS;

/** Registered operations with no handler binding yet. */
export const UNIMPLEMENTED_OPERATIONS = ${JSON.stringify(unimplemented, null, "\t")} as const satisfies readonly OperationId[];
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "validators.js"), validatorsJs);
writeFileSync(join(outDir, "validators.d.ts"), validatorsDts);
writeFileSync(join(outDir, "types.ts"), types);
writeFileSync(join(outDir, "operations.ts"), operationsTs);
console.log(
	`codegen: ${files.length} schemas, ${Object.keys(sortedRefs).length} validators, ${ops.length} operations -> ${outDir}`,
);
